name: Team21-OpsDev-CD

on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        required: false

jobs:
  your_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
