name: Team21-OpsDev-CD
            
on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        required: false

jobs:
  your_job:
    runs-on: ubuntu-latest

    steps:
            - name: Docker Login
              uses: docker/login-action@v3.0.0
              with:
                      username: ${{ secrets.dietmardamiaens }}
                      password: ${{ secrets.dietmardamiaens }}

            - name: Build and push Docker images
              uses: docker/build-push-action@v5.1.0

            - name: Notify Discord
              uses: Ilshidur/action-discord@v1
              with:
                type: text
                content: "Deployment successful! Opdracht 8 discord webhook werkt."
                token: ${{ secrets.DISCORDWEBHOOK }}
