name: Team21-OpsDev-azureDeploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
                      username: ${{ secrets.DOCKERHUB_NAME }}
                      password: ${{ secrets.DOCKERHUB_ACCESTOKEN }}
        
    - name: Build and push Docker image
      run: |
        docker build -t your-docker-image-name .
        docker push your-docker-image-name

    - name: Deploy to Azure App Service
      run: |
        az webapp config container set --name your-app-name --resource-group your-resource-group --docker-custom-image-name your-docker-image-name

    - name: Deploy complete
      run: |
        echo "Application deployed successfully to Azure App Service."
